name: Sync
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Opening pull request
        id: pull
        uses: sansx/sync-branches@1.0.0
        with:
          PULL_REQUEST_TITLE: "Sync main to demo"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PULL_REQUEST_AUTO_MERGE_METHOD: "squash"
          FROM_BRANCH: "main"
          TO_BRANCH: "demo"
